type AdditiveSymbolSet = Array<[number, string]>

export const unorderedListStyleSymbols: Array<[string, string | null]> = [
  ['none', null],
  ['disc', '\u2022'],
  ['circle', '\u25e6'],
  ['square', '\u25aa'],
  ['disclosure-open', '\u25be'],
  ['disclosure-closed', '\u25b8'],
]

const upperArmenianSymbols: AdditiveSymbolSet = [
  [9000, 'Ք'],
  [8000, 'Փ'],
  [7000, 'Ւ'],
  [6000, 'Ց'],
  [5000, 'Ր'],
  [4000, 'Տ'],
  [3000, 'Վ'],
  [2000, 'Ս'],
  [1000, 'Ռ'],
  [900, 'Ջ'],
  [800, 'Պ'],
  [700, 'Չ'],
  [600, 'Ո'],
  [500, 'Շ'],
  [400, 'Ն'],
  [300, 'Յ'],
  [200, 'Մ'],
  [100, 'Ճ'],
  [90, 'Ղ'],
  [80, 'Ձ'],
  [70, 'Հ'],
  [60, 'Կ'],
  [50, 'Ծ'],
  [40, 'Խ'],
  [30, 'Լ'],
  [20, 'Ի'],
  [10, 'Ժ'],
  [9, 'Թ'],
  [8, 'Ը'],
  [7, 'Է'],
  [6, 'Զ'],
  [5, 'Ե'],
  [4, 'Դ'],
  [3, 'Գ'],
  [2, 'Բ'],
  [1, 'Ա'],
]

const lowerArmenianSymbols: AdditiveSymbolSet = [
  [9000, 'ք'],
  [8000, 'փ'],
  [7000, 'ւ'],
  [6000, 'ց'],
  [5000, 'ր'],
  [4000, 'տ'],
  [3000, 'վ'],
  [2000, 'ս'],
  [1000, 'ռ'],
  [900, 'ջ'],
  [800, 'պ'],
  [700, 'չ'],
  [600, 'ո'],
  [500, 'շ'],
  [400, 'ն'],
  [300, 'յ'],
  [200, 'մ'],
  [100, 'ճ'],
  [90, 'ղ'],
  [80, 'ձ'],
  [70, 'հ'],
  [60, 'կ'],
  [50, 'ծ'],
  [40, 'խ'],
  [30, 'լ'],
  [20, 'ի'],
  [10, 'ժ'],
  [9, 'թ'],
  [8, 'ը'],
  [7, 'է'],
  [6, 'զ'],
  [5, 'ե'],
  [4, 'դ'],
  [3, 'գ'],
  [2, 'բ'],
  [1, 'ա'],
]

const georgianSymbols: AdditiveSymbolSet = [
  [10000, 'ჶ'],
  [9000, 'ჵ'],
  [8000, 'ჰ'],
  [7000, 'ჯ'],
  [6000, 'ხ'],
  [5000, 'ჭ'],
  [4000, 'წ'],
  [3000, 'ძ'],
  [2000, 'ც'],
  [1000, 'ჩ'],
  [900, 'შ'],
  [800, 'ყ'],
  [700, 'ღ'],
  [600, 'ქ'],
  [500, 'ფ'],
  [400, 'უ'],
  [300, 'ტ'],
  [200, 'ს'],
  [100, 'რ'],
  [90, 'ჟ'],
  [80, 'პ'],
  [70, 'ო'],
  [60, 'ჲ'],
  [50, 'ნ'],
  [40, 'მ'],
  [30, 'ლ'],
  [20, 'კ'],
  [10, 'ი'],
  [9, 'თ'],
  [8, 'ჱ'],
  [7, 'ზ'],
  [6, 'ვ'],
  [5, 'ე'],
  [4, 'დ'],
  [3, 'გ'],
  [2, 'ბ'],
  [1, 'ა'],
]

const lowerLatinSymbols = 'abcdefghijklmnopqrstuvwxyz'.split('')
const upperLatinSymbols = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')
const lowerNorwegianSymbols = 'abcdefghijklmnopqrstuvwxyzæøå'.split('')
const upperNorwegianSymbols = 'ABCDEFGHIJKLMNOPQRSTUVWXYZÆØÅ'.split('')
const arabicIndicDigits = '٠١٢٣٤٥٦٧٨٩'.split('')
const persianDigits = '۰۱۲۳۴۵۶۷۸۹'.split('')
const devanagariDigits = '०१२३४५६७८९'.split('')
const bengaliDigits = '০১২৩৪৫৬৭৮৯'.split('')
const gurmukhiDigits = '੦੧੨੩੪੫੬੭੮੯'.split('')
const gujaratiDigits = '૦૧૨૩૪૫૬૭૮૯'.split('')
const kannadaDigits = '೦೧೨೩೪೫೬೭೮೯'.split('')
const malayalamDigits = '൦൧൨൩൪൫൬൭൮൯'.split('')
const tamilDigits = '௦௧௨௩௪௫௬௭௮௯'.split('')
const teluguDigits = '౦౧౨౩౪౫౬౭౮౯'.split('')
const thaiDigits = '๐๑๒๓๔๕๖๗๘๙'.split('')
const laoDigits = '໐໑໒໓໔໕໖໗໘໙'.split('')
const myanmarDigits = '၀၁၂၃၄၅၆၇၈၉'.split('')
const khmerDigits = '០១២៣៤៥៦៧៨៩'.split('')
const mongolianDigits = '᠐᠑᠒᠓᠔᠕᠖᠗᠘᠙'.split('')
const oriyaDigits = '୦୧୨୩୪୫୬୭୮୯'.split('')
const tibetanDigits = '༠༡༢༣༤༥༦༧༨༩'.split('')
export const cjkDecimalDigits = '〇一二三四五六七八九'.split('')

const lowerGreekSymbols = [
  '\u03b1',
  '\u03b2',
  '\u03b3',
  '\u03b4',
  '\u03b5',
  '\u03b6',
  '\u03b7',
  '\u03b8',
  '\u03b9',
  '\u03ba',
  '\u03bb',
  '\u03bc',
  '\u03bd',
  '\u03be',
  '\u03bf',
  '\u03c0',
  '\u03c1',
  '\u03c3',
  '\u03c4',
  '\u03c5',
  '\u03c6',
  '\u03c7',
  '\u03c8',
  '\u03c9',
]
const lowerCyrillicSymbols = [
  'а',
  'б',
  'в',
  'г',
  'д',
  'е',
  'ж',
  'з',
  'и',
  'й',
  'к',
  'л',
  'м',
  'н',
  'о',
  'п',
  'р',
  'с',
  'т',
  'у',
  'ф',
  'х',
  'ц',
  'ч',
  'ш',
  'щ',
  'ъ',
  'ы',
  'ь',
  'э',
  'ю',
  'я',
]
const upperCyrillicSymbols = lowerCyrillicSymbols.map((symbol) =>
  symbol.toUpperCase()
)
const hiraganaSymbols = [
  'あ',
  'い',
  'う',
  'え',
  'お',
  'か',
  'き',
  'く',
  'け',
  'こ',
  'さ',
  'し',
  'す',
  'せ',
  'そ',
  'た',
  'ち',
  'つ',
  'て',
  'と',
  'な',
  'に',
  'ぬ',
  'ね',
  'の',
  'は',
  'ひ',
  'ふ',
  'へ',
  'ほ',
  'ま',
  'み',
  'む',
  'め',
  'も',
  'や',
  'ゆ',
  'よ',
  'ら',
  'り',
  'る',
  'れ',
  'ろ',
  'わ',
  'を',
  'ん',
]
const katakanaSymbols = [
  'ア',
  'イ',
  'ウ',
  'エ',
  'オ',
  'カ',
  'キ',
  'ク',
  'ケ',
  'コ',
  'サ',
  'シ',
  'ス',
  'セ',
  'ソ',
  'タ',
  'チ',
  'ツ',
  'テ',
  'ト',
  'ナ',
  'ニ',
  'ヌ',
  'ネ',
  'ノ',
  'ハ',
  'ヒ',
  'フ',
  'ヘ',
  'ホ',
  'マ',
  'ミ',
  'ム',
  'メ',
  'モ',
  'ヤ',
  'ユ',
  'ヨ',
  'ラ',
  'リ',
  'ル',
  'レ',
  'ロ',
  'ワ',
  'ヲ',
  'ン',
]
const hiraganaIrohaSymbols = [
  'い',
  'ろ',
  'は',
  'に',
  'ほ',
  'へ',
  'と',
  'ち',
  'り',
  'ぬ',
  'る',
  'を',
  'わ',
  'か',
  'よ',
  'た',
  'れ',
  'そ',
  'つ',
  'ね',
  'な',
  'ら',
  'む',
  'う',
  'ゐ',
  'の',
  'お',
  'く',
  'や',
  'ま',
  'け',
  'ふ',
  'こ',
  'え',
  'て',
  'あ',
  'さ',
  'き',
  'ゆ',
  'め',
  'み',
  'し',
  'ゑ',
  'ひ',
  'も',
  'せ',
  'す',
]
const katakanaIrohaSymbols = [
  'イ',
  'ロ',
  'ハ',
  'ニ',
  'ホ',
  'ヘ',
  'ト',
  'チ',
  'リ',
  'ヌ',
  'ル',
  'ヲ',
  'ワ',
  'カ',
  'ヨ',
  'タ',
  'レ',
  'ソ',
  'ツ',
  'ネ',
  'ナ',
  'ラ',
  'ム',
  'ウ',
  'ヰ',
  'ノ',
  'オ',
  'ク',
  'ヤ',
  'マ',
  'ケ',
  'フ',
  'コ',
  'エ',
  'テ',
  'ア',
  'サ',
  'キ',
  'ユ',
  'メ',
  'ミ',
  'シ',
  'ヱ',
  'ヒ',
  'モ',
  'セ',
  'ス',
]

export const additiveListStyleSymbols: Array<[string[], AdditiveSymbolSet]> = [
  [['armenian', 'upper-armenian'], upperArmenianSymbols],
  [['lower-armenian'], lowerArmenianSymbols],
  [['georgian'], georgianSymbols],
]

export const alphabeticListStyleSymbols: Array<[string[], string[]]> = [
  [['upper-alpha', 'upper-latin'], upperLatinSymbols],
  [['lower-alpha', 'lower-latin'], lowerLatinSymbols],
  [['lower-norwegian', 'lower-danish'], lowerNorwegianSymbols],
  [['upper-norwegian', 'upper-danish'], upperNorwegianSymbols],
  [['lower-greek'], lowerGreekSymbols],
  [['lower-cyrillic'], lowerCyrillicSymbols],
  [['upper-cyrillic'], upperCyrillicSymbols],
  [['hiragana'], hiraganaSymbols],
  [['hiragana-iroha'], hiraganaIrohaSymbols],
  [['katakana'], katakanaSymbols],
  [['katakana-iroha'], katakanaIrohaSymbols],
]

export const numericListStyleSymbols: Array<[string, string[]]> = [
  ['arabic-indic', arabicIndicDigits],
  ['persian', persianDigits],
  ['devanagari', devanagariDigits],
  ['bengali', bengaliDigits],
  ['gurmukhi', gurmukhiDigits],
  ['gujarati', gujaratiDigits],
  ['kannada', kannadaDigits],
  ['malayalam', malayalamDigits],
  ['tamil', tamilDigits],
  ['telugu', teluguDigits],
  ['thai', thaiDigits],
  ['lao', laoDigits],
  ['myanmar', myanmarDigits],
  ['khmer', khmerDigits],
  ['cambodian', khmerDigits],
  ['mongolian', mongolianDigits],
  ['oriya', oriyaDigits],
  ['tibetan', tibetanDigits],
]
