import type { SerializedStyle } from './style-types.js'

export const CSS_ALL_UNSET_INHERITED_PROP_NAMES = [
  'color',
  'fontFamily',
  'fontSize',
  'fontStyle',
  'fontWeight',
  'fontVariant',
  'fontVariantCaps',
  'fontVariantPosition',
  'fontSizeAdjust',
  'letterSpacing',
  'lineHeight',
  'textAlign',
  'textAlignLast',
  'textJustify',
  'textTransform',
  'textShadowOffset',
  'textShadowColor',
  'textShadowRadius',
  'WebkitTextStrokeWidth',
  'WebkitTextStrokeColor',
  'textDecorationLine',
  'textDecorationStyle',
  'textDecorationColor',
  'textDecorationSkipInk',
  'textUnderlinePosition',
  'whiteSpace',
  'wordBreak',
  'overflowWrap',
  'hyphens',
  'hyphenateCharacter',
  'hyphenateLimitChars',
  'tabSize',
  'visibility',
  'cursor',
  'wordSpacing',
  'textIndent',
  'listStyleType',
  'listStylePosition',
  'listStyleImage',
] as const

export const CSS_ALL_INITIAL_STYLE: SerializedStyle = {
  color: 'black',
  fontFamily: ['serif'],
  fontSize: 16,
  fontStyle: 'normal',
  fontWeight: 'normal',
  fontVariant: 'normal',
  fontVariantCaps: 'normal',
  fontVariantPosition: 'normal',
  fontSizeAdjust: 'none',
  lineHeight: 'normal',
  letterSpacing: 0,
  textAlign: 'start',
  textAlignLast: 'auto',
  textJustify: 'auto',
  textTransform: 'none',
  whiteSpace: 'normal',
  wordBreak: 'normal',
  overflowWrap: 'normal',
  hyphens: 'manual',
  hyphenateCharacter: 'auto',
  hyphenateLimitChars: 'auto',
  tabSize: 8,
  listStyleType: 'disc',
  listStylePosition: 'outside',
  listStyleImage: 'none',
  counterReset: 'none',
  counterIncrement: 'none',
  counterSet: 'none',
  wordSpacing: 0,
  textIndent: 0,
  visibility: 'visible',
  cursor: 'auto',
  touchAction: 'auto',
  userSelect: 'auto',
  opacity: 1,
  filter: 'none',
  textDecorationLine: 'none',
  textDecorationStyle: 'solid',
  textDecorationSkipInk: 'auto',
  textUnderlinePosition: 'auto',
  backgroundColor: 'transparent',
  backgroundRepeat: 'repeat',
  backgroundPosition: '0% 0%',
  backgroundSize: 'auto',
  backgroundClip: 'border-box',
  backgroundOrigin: 'padding-box',
  mixBlendMode: 'normal',
  isolation: 'auto',
  maskImage: 'none',
}
