export const CSS_ALL_UNSET_INHERITED_PROPS = new Set([
  'color',
  'fontFamily',
  'fontSize',
  'fontStyle',
  'fontWeight',
  'fontSizeAdjust',
  'letterSpacing',
  'lineHeight',
  'textAlign',
  'textAlignLast',
  'textJustify',
  'textTransform',
  'textShadowOffset',
  'textShadowColor',
  'textShadowRadius',
  'WebkitTextStrokeWidth',
  'WebkitTextStrokeColor',
  'textDecorationLine',
  'textDecorationStyle',
  'textDecorationColor',
  'textDecorationSkipInk',
  'textUnderlinePosition',
  'whiteSpace',
  'wordBreak',
  'overflowWrap',
  'tabSize',
  'visibility',
  'cursor',
  'wordSpacing',
  'textIndent',
  'listStyleType',
  'listStylePosition',
  'listStyleImage',
])

export const RUNTIME_INHERITED_PROPS = new Set([
  ...CSS_ALL_UNSET_INHERITED_PROPS,

  // Extra properties that need manual propagation in Satori's rendering model.
  'font',
  'fontKerning',
  'transform',
  'touchAction',
  'userSelect',
  'opacity',
  'filter',

  // Internal rendering context fields.
  '_viewportWidth',
  '_viewportHeight',
  '_inheritedClipPathId',
  '_inheritedMaskId',
  '_inheritedBackgroundClipTextPath',
  '_inheritedBackgroundClipTextHasBackground',
])
